apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: disearch-secret-provider-class
  namespace: airflow
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/YOUR_PROJECT_ID/secrets/DB_HOST/versions/latest"
        path: "db_host"
      - resourceName: "projects/YOUR_PROJECT_ID/secrets/DB_PASSWORD/versions/latest"
        path: "db_password"
      - resourceName: "projects/YOUR_PROJECT_ID/secrets/DB_USER/versions/latest"
        path: "db_user"

